services:
  db:
    build:
      context: .
      dockerfile: db/db.Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  ingestion:
    build:
      context: .
      dockerfile: ingestion/ingestion.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: "no"

  api:
    build:
      context: .
      dockerfile: api/api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: dashboard/dashboard.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api

volumes:
  postgres_data: